### ISSUE TITLE
Action Overflow Menu disappears on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [billthefarmer/currency#10]
When i perform this sequence of events, the menu disappears:

1. Click on ... (More Options)
2. Orientation Change

**Comment by billthefarmer** [comment]
OK, I haven't found if this is possible or a mention anywhere yet.

**Comment by billthefarmer** [comment]
It took me a while, but I just realised why this is so. The system adjusts the number of items on the toolbar according to orientation. On a phone, you get three items in portrait, and four in landscape unless you override the defaults. So with four items in the menu, in portrait you get a overflow menu with two items as the icon for the overflow menu uses the third toolbar slot. When you rotate the phone, the overflow menu disappears because the items fit on the toolbar. On another project of mine, with more items in the menu, the size of the overflow menu gets adjusted on rotation. This doesn't happen on a tablet because you get four items on the toolbar in portrait.
