### ISSUE TITLE
Dot . as a decimal point ignored

### ISSUE THREAD

**Issue by Aralun** [billthefarmer/currency#23]
General info:
- OS: Android 7.0
- Phone: Huawei Honor 6X
- Currency version: 1.10
- Application installed from F-Droid

The immediately-available dot (`.`) is ignored as shown in the first screenshot.
Using the sub-menu comma (`,`) works as shown in the other screenshot.

<details>
<summary>First screenshot - dot</summary>
<div><img src="https://user-images.githubusercontent.com/4149052/32145009-7e92f088-bcca-11e7-9262-be76000aeb41.png" alt="First screenshot"/></div>
</details>

<details>
<summary>Second screenshot - comma</summary>
<div><img src="https://user-images.githubusercontent.com/4149052/32145032-c5afee62-bcca-11e7-8d25-dec7dd0d4280.png" alt="Second screenshot"/></div>
</details>
<br/>

This relates to #13 except it's the other way around.
This happens both with the native keyboard (Gboard) and [Hacker's Keyboard](https://f-droid.org/packages/org.pocketworkstation.pckeyboard/).

**Comment by billthefarmer** [comment]
There are two separate issues here, the keyboard and parsing of decimal numbers. There was a bug in the keyboard referred to in #13 which I worked around by making both dot and comma acceptable input characters for all locales. The issue with parsing is that the dot and comma mean opposite things in different locales. You seem to be using a non-English locale because the numbers are being displayed with a comma for the decimal point. Therefore I think that behavior is correct, the dot is being ignored because for your locale it is just to make large numbers more readable. In the first screenshot you seem to have the keyboard set to English, which isn't going to change the parsing, which is specific for each locale.

**Comment by Aralun** [comment]
Indeed, French locale here. Therefore it's a feature?

**Comment by billthefarmer** [comment]
No, it's working as it should. The numeric input uses the same convention as the display. If you wan't to use English conventions set the language to English.

**Comment by Aralun** [comment]
I see. Providing an option to choose the kind of separator the user wants might be too cumbersome to reproduce for different locales and is anyway outside the scope of a bug report.

Thanks for the quick reaction!

**Comment by billthefarmer** [comment]
Perhaps I should explain in a bit more detail. The code that parses decimal input is [here](https://github.com/billthefarmer/currency/blob/88e58739cdbb9bce0e392348f5864fa331d4c97a/src/main/java/org/billthefarmer/currency/Main.java#L925). It uses `NumberFormat.getInstance()` to get a [number formatter and parser](https://developer.android.com/reference/java/text/NumberFormat.html#getInstance()) for the current locale which is used for parsing the input and formatting the output. So the numeric input and output uses the conventions for the locale that the device has been set to.

You seem to want an option to use a locale of your choice for numeric input and output independent of the language the device is set to. All things are possible, of course, but it would be an exceedingly long list of languages. See `Settings app-> Languages & input->Virtual keyboard->Android Keyboard (or whatever you have)->Languages`.
