### ISSUE TITLE
Comma and decimal point issue

### ISSUE THREAD

**Issue by Ollo1** [billthefarmer/currency#27]
Info:
    OS: Android 7.0
    Phone: Samsung Galaxy S7
    Currency version: 1.14

Hello,
similar to #13 and #23 I have an issue which I assume is related to the Samsung keyboard and German language seetings. As seen on the screenshot there is no option to use a comma with the Samsung Keyboard on a Galaxy S7 (at least I didn't find). If I use the decimal point it is considered like in the US.

![screenshot](https://user-images.githubusercontent.com/26634910/34960418-021c80b0-fa3b-11e7-8cb1-2d0ebc93f99c.png)

**Comment by billthefarmer** [comment]
Because of the problems with android numeric keyboards I have changed the input function to accept either a dot or comma, and to first attempt to parse the input using the locale that the phone has been set to, and if that fails, to use the English locale. Hopefully it will then get it right. This doesn't affect the display, which uses the current locale. Users seem to have conflicting views as to which is correct.

I have just tested this on my phone. Unfortunately the parser ignores the stop character and doesn't fail when the language is set to German. There is not much I can do about the Samsung numeric keyboard.

**Comment by Ollo1** [comment]
Thanks for the feedback. I understood your answer in the way that I might need to consider switching the default keyboard as any change on the Samsung keyboard I tried (Englisch, German) layout even changing the system language didn't change anything on the numeric keyboard. There is always only the decimal point available. As a workaround I use the default comma in your edit field and change only the numbers.

**Comment by Ollo1** [comment]
Just an addition which might help. I use also MoneyManagerEx (https://github.com/moneymanagerex) which use a different style of a numeric keyboard and shows the german comma while it internally use only the decimal point as seen on the screenshot.
![screenshot_20180123-065714](https://user-images.githubusercontent.com/26634910/35343089-01769d44-012a-11e8-922f-85f075f01bbe.png)

**Comment by Ollo1** [comment]
Sorry to bother again. But what do you mean by the blank slots? 
I know that a Gboard or other keyboard might be an option but I'm pretty happy with the Samsung Keyboard.

**Comment by billthefarmer** [comment]
The two buttons on either size of the zero button.

**Comment by Ollo1** [comment]
Unfortunate those buttons do not have any function at all.
