### ISSUE TITLE
Feature Request: Allow re-ordering of list of currencies by dragging currencies

### ISSUE THREAD

**Issue by ghost** [billthefarmer/currency#48]
Hi,
I have a feature suggestion. I'd really like to be able to re-order the list of currencies in the app by dragging currencies in the list. Say for example, allow the user to tap and hold then drag a currency to move it up or down in the list of currencies.

Would it be possible to add that functionality?

Thanks.

**Comment by billthefarmer** [comment]
I will investigate, but I don't think it's likely because the list will scroll if long enough, it's the same functionality as the currency list in the add a currency pop-up. I think I investigated that when I was developing the app. You can reorder the list by tapping on each entry in the reverse order you want them. The first one you tap on will end up at the end of the list and so on.

**Comment by billthefarmer** [comment]
I have tested this, hijacking the touch events stops the normal functionality working - select, etc.

**Comment by AluminiumTech** [comment]
> I have tested this, hijacking the touch events stops the normal functionality working - select, etc.

Ooof. Is there a way that the existing selection functionality could be improved then to make it more intuitive?

**Comment by billthefarmer** [comment]
The selection logic appears to be fairly standard - tap for new default currency, long press to select, tap to add or remove from selection, another long press to start another selection. I could make the old default currency move to the end of the list instead of the top. then you could reorder by tapping in the order you want.
