### ISSUE TITLE
Add custom URL for data

### ISSUE THREAD

**Issue by GitHubHatesTor** [billthefarmer/currency#6]
related to https://github.com/billthefarmer/currency/issues/1

>    public static final String ECB_URL =
>	"http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml";

When I tried to access http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml via Tor(Orbot/Android),
"
A problem occurred while trying to access this page
We apologize for any inconvenience this might have caused.
Reference number: #xxxxxxxxxxx
HTTP status code: 403
"

So, let the user change this URL to someone else.

(If I know the data type of this XML file, I could make a original XML file and release it on my website. For example, BTC-to-USD conversion.)

**Comment by billthefarmer** [comment]
I have checked this using the Tor browser. It looks like the ECB denies access to it's web site to the Tor network. This app uses the ECB data specifically because it is free to access, is updated daily and provides rates for 32 currencies. Also the data format is simple to decode using SAX. Any alternative site would need to get currency data and encode it in the same format for the same currencies.
