### ISSUE TITLE
wifi vs roaming

### ISSUE THREAD

**Issue by opk12** [billthefarmer/currency#64]
Updating works, but it feels counterintuitive:
- Why is the wifi vs roaming choice relevant for the Update button (is a lot of data transferred)?
- Charting appears to ignore it?
- Connect to wifi and not mobile data. Check `update on roaming` and not `update only on wifi`. The Update button works.
- This is cosmetic, but when connected to mobile data and not wifi, it's weird to see both checked and the Update button not working (`no WiFi`).

**Comment by billthefarmer** [comment]
The amount of data transferred in normal use is small. However the historical feature in the chart loads data dating back to 1 Jan 1999, which will be several Mb. The update on WiFi only setting won't load from mobile data because for some people on real PAYG tariffs that can be expensive, just to use it. For people on normal tariffs who have mobile data on all the time, just turn it off. Again, on some tariffs, using roaming when you don't have coverage from your operator can be expensive. If that's not a problem, turn it off.

There are three errors you can get. If there is no connection you get 'no connection'. If you've selected wifi only and there isn't any you get 'no wifi'. If you are roaming and you haven't selected roaming, you get 'roaming'.

The data only gets updated once a weekday by the ECB, so there's no point in updating unless the date shown is old. The app always has a copy of the last update, so will be current unless you don't use it for a while.
