### ISSUE TITLE
Dialog disappears on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [billthefarmer/currency#8]
When i perform these sequences of events, the dialog on screen disappears:

Sequence 1-2:
1. Click on ...
2. Click on Settings
3. Click on:
a. Fraction Digits
b. About
4. Orientation Change

**Comment by billthefarmer** [comment]
Not sure about that one either. Further investigation required.

**Comment by reverse-unina** [comment]
As regards to dialogs I send you a pointer from Android guidelines.
Source: https://developer.android.com/guide/topics/ui/dialogs.html

The Dialog class is the base class for dialogs, but you should avoid instantiating Dialog directly[...]
[AlertDialog et al.] classes define the style and structure for your dialog, but you should use a DialogFragment as a container for your dialog. The DialogFragment class provides all the controls you need to create your dialog and manage its appearance, instead of calling methods on the Dialog object.

Using DialogFragment to manage the dialog ensures that it correctly handles lifecycle events such as when the user presses the Back button or rotates the screen.

**Comment by billthefarmer** [comment]
Both these dialogs are subclasses of PreferenceDialog, so the above does not apply. The about dialog in my Shorty app does not do this because it is not part of the preference system. The fraction digits dialog is a ListPreference and is defined by xml code in the application preferences file. The only application code associated with it shows the current value in the preference screen. The about dialog is similar, except there is code to fill in the app version. The dialogs are displayed and dismissed by the preference system on user interaction with no application code involved. There is an API for preserving the state of custom preference dialogs, but no control offered as to how they are displayed and dismissed.
