### ISSUE TITLE
Scrollable view changes state on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [billthefarmer/currency#9]
When I perform this sequence of events, the scrollable view on screen goes back to the top:

Sequence 1:
1. Scroll Down the currency list
2. Orientation Change

Sequence 2:
1. Click on ...
2. Click on Help
3. Scroll Down
4. Orientation Change

**Comment by billthefarmer** [comment]
The currency list problem is fixed in the next version. According to the documentation, if you give the views in your application ids, then their state should be saved and restored by the system. This works with the ListView showing the currency lists, but not with the ScrollView showing the help text. In fact the documentation for ScrollView.onSaveInstanceState() says the default implementation returns null.

onSaveInstanceState
Returns
Parcelable 	Returns a Parcelable object containing the view's current dynamic state, or null if there is nothing interesting to save. The default implementation returns null.
